version: "3"

services:
  asr:
    build: .
    volumes:
      - /media/kaldi_models:/opt/test/models
      - ./sample_english_nnet2.yaml:/opt/test/models/sample_english_nnet2.yaml
    ports:
      - "9999:80"